# Generated by Django 4.2.18 on 2025-03-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitals", "0003_alter_staff_num_licence"),
        (
            "patients",
            "0002_alter_patient_age_in_days_alter_patient_birth_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de connexion"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logins",
                        to="hospitals.staff",
                        verbose_name="Personnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connexion du personnel",
                "verbose_name_plural": "Connexions du personnel",
            },
        ),
        migrations.CreateModel(
            name="RMSHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_changed",
                    models.CharField(max_length=100, verbose_name="Champ modifié"),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Ancienne valeur"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Nouvelle valeur"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rms_modifications",
                        to="hospitals.staff",
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "rms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="patients.rms",
                        verbose_name="RMS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique RMS",
                "verbose_name_plural": "Historique RMS",
            },
        ),
        migrations.CreateModel(
            name="ConsultationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de consultation"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "rms",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="patients.rms",
                        verbose_name="RMS",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="hospitals.staff",
                        verbose_name="Personnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de consultation",
                "verbose_name_plural": "Historique des consultations",
            },
        ),
    ]
