# Generated by Django 4.2.18 on 2025-03-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0003_alter_staff_num_licence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affiliation",
            options={
                "verbose_name": "Affiliation",
                "verbose_name_plural": "Affiliations",
            },
        ),
        migrations.AlterModelOptions(
            name="hospital",
            options={"verbose_name": "Hôpital", "verbose_name_plural": "Hôpitaux"},
        ),
        migrations.AlterModelOptions(
            name="speciality",
            options={
                "verbose_name": "Spécialité",
                "verbose_name_plural": "Spécialités",
            },
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={"verbose_name": "Personnel", "verbose_name_plural": "Personnel"},
        ),
        migrations.AlterModelOptions(
            name="staffstatushistory",
            options={
                "verbose_name": "Historique des statuts",
                "verbose_name_plural": "Historique des statuts",
            },
        ),
        migrations.RemoveField(
            model_name="staff",
            name="num_licence",
        ),
        migrations.AddField(
            model_name="staff",
            name="doctor_order_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="nurse_order_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="student_matricule",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="type",
            field=models.CharField(
                choices=[
                    ("doctor", "Médecin"),
                    ("des", "Docteur En Spécialisation"),
                    ("idh", "Interne Des Hôpitaux"),
                    ("intern", "Interne"),
                    ("nurse", "Infirmier"),
                ],
                default="doctor",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffstatushistory",
            name="new_type",
            field=models.CharField(
                choices=[
                    ("doctor", "Médecin"),
                    ("des", "Docteur En Spécialisation"),
                    ("idh", "Interne Des Hôpitaux"),
                    ("intern", "Interne"),
                    ("nurse", "Infirmier"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffstatushistory",
            name="old_type",
            field=models.CharField(
                choices=[
                    ("doctor", "Médecin"),
                    ("des", "Docteur En Spécialisation"),
                    ("idh", "Interne Des Hôpitaux"),
                    ("intern", "Interne"),
                    ("nurse", "Infirmier"),
                ],
                max_length=20,
            ),
        ),
    ]
