# Generated by Django 4.2.18 on 2025-03-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0004_alter_affiliation_options_alter_hospital_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="first_name",
            field=models.CharField(default=2, max_length=255, verbose_name="Prénom(s)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="name",
            field=models.CharField(default=3, max_length=100, verbose_name="Nom"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="sex",
            field=models.CharField(
                choices=[("Homme", "Homme"), ("Femmme", "Femme")],
                default=3,
                max_length=20,
                verbose_name="Sex",
            ),
            preserve_default=False,
        ),
    ]
