# Generated by Django 4.2.18 on 2025-03-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0005_staff_first_name_staff_name_staff_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Photo de profil"
            ),
        ),
    ]
