# Generated by Django 4.2.18 on 2025-03-23 12:31

from django.db import migrations, models
import hospitals.models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0006_staff_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="phone",
            field=models.CharField(blank=True, max_length=15, verbose_name="Telephone"),
        ),
        migrations.RemoveField(
            model_name="staff",
            name="specialities",
        ),
        migrations.AlterField(
            model_name="staff",
            name="type",
            field=models.CharField(
                choices=[
                    ("doctor", "Médecin"),
                    ("des", "Docteur En Spécialisation"),
                    ("idh", "Interne Des Hôpitaux"),
                    ("intern", "Interne"),
                    ("nurse", "Infirmier"),
                ],
                default="doctor",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="specialities",
            field=models.OneToOneField(
                blank=True,
                default=1,
                on_delete=hospitals.models.Speciality,
                to="hospitals.speciality",
                verbose_name="Specialité",
            ),
            preserve_default=False,
        ),
    ]
