# Generated by Django 4.2.18 on 2025-03-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0003_alter_staff_num_licence"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age_in_days",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Âge en jours pour bébés de moins de 2 ans",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="birth_year_approx",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Année approximative de naissance  (ex. : né vers 1995)",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Adresse e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="estimated_age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Âge estimé en années si rien d’autre",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(max_length=250, verbose_name="Prénom(s)"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Nom de famille"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="num_identifier",
            field=models.CharField(
                default="bf86f5b08260",
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Numéro d’identification",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Numéro de téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="rms",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="rms",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rms_created",
                to="hospitals.staff",
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="rms",
            name="fhir_data",
            field=models.JSONField(default=dict, verbose_name="Données FHIR"),
        ),
        migrations.AlterField(
            model_name="rms",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rms_records",
                to="hospitals.hospital",
                verbose_name="Hôpital",
            ),
        ),
        migrations.AlterField(
            model_name="rms",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rms_records",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="rms",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="rms",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rms_updated",
                to="hospitals.staff",
                verbose_name="Mis à jour par",
            ),
        ),
    ]
