# Generated by Django 4.2.18 on 2025-03-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0004_alter_affiliation_options_alter_hospital_options_and_more"),
        (
            "patients",
            "0002_alter_patient_age_in_days_alter_patient_birth_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consent",
            options={
                "verbose_name": "Consentement",
                "verbose_name_plural": "Consentements",
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "Patient", "verbose_name_plural": "Patients"},
        ),
        migrations.AlterModelOptions(
            name="rms",
            options={"verbose_name": "RMS", "verbose_name_plural": "RMS"},
        ),
        migrations.AlterField(
            model_name="patient",
            name="estimated_age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Âge estimé en années si rien d'autre",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="main_hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="hospitals.hospital",
                verbose_name="Hôpital",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="num_identifier",
            field=models.CharField(
                default="559bdf4c219a",
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Numéro d'identification",
            ),
        ),
    ]
