# Generated by Django 4.2.18 on 2025-03-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_consent_options_alter_patient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="num_identifier",
            field=models.CharField(
                default="a825c1c11984",
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Numéro d'identification",
            ),
        ),
    ]
