# Generated by Django 4.2.18 on 2025-03-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_alter_patient_num_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="num_identifier",
            field=models.CharField(
                default="ccb0b68a13fd",
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Numéro d'identification",
            ),
        ),
    ]
